### ISSUE TITLE
[Question] Efficiency of Runtime.addShutdownHook

### ISSUE THREAD

**Issue by RobbWatershed** [tom5079/DocumentFileX#1]
I've seen you're using `Runtime.addShutdownHook` to schedule cache cleanup in https://github.com/tom5079/DocumentFileX/blob/4835cda39a14e74f90c9a0805c676b24e10b5139/library/src/main/java/xyz/quaver/io/util/DeleteOnExitHook.kt#L60

I'd like to know your feedback about the efficiency of this (i.e. has it been tested successfuly on various real-world devices ?), as the documentation of this method mostly describes what happens around the Java VM, and is not clear at all about what it means for an Android app.

Alternatively, have you considered giving users the possibility of calling the hook from their app ?

**Comment by tom5079** [comment]
I don't know how efficient it is, the code is from [Android SDK](https://cs.android.com/android/platform/superproject/+/master:libcore/ojluni/src/main/java/java/io/DeleteOnExitHook.java)

It is used to implement [File.deleteOnExit()](https://github.com/tom5079/DocumentFileX/blob/2a916db0a67406df9cf7755153ae0f02e8735ac0/library/src/main/java/xyz/quaver/io/SAFileX.kt#L53) and it is not related to cache cleanup

I didn't test the method or the class but I think it will work generally well because it's directly from Android SDK :)

**Comment by tom5079** [comment]
Oh well, it will definitely not work because of the uninitialized `context` variable :joy: 

I'll fix it too, thanks.

**Comment by RobbWatershed** [comment]
Maybe I'll do some tests on my end. At least my comment was useful for something ;)

**Comment by tom5079** [comment]
Appreciate it, it'll help :)
